// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/claros-reference/Homepage.tsx": () => import("../components/mockups/claros-reference/Homepage.tsx")
};
