"""Pure Claros V2 lifecycle models, services, and invariants."""

from backend.domain.errors import (
    AssignmentExpired,
    AssignmentVersionConflict,
    CandidateNotFound,
    DomainError,
    InvalidCandidate,
    InvalidCandidateOrigin,
    InvalidQuestionSetup,
    NoConfirmedAnswers,
    QuestionNotFound,
    QuestionSetupLocked,
    QuestionSetupUnverified,
    ReviewTokenExpired,
    ReviewTokenInvalid,
    ReviewTokenStale,
)
from backend.domain.models import (
    AssignmentManifest,
    AssignmentStatus,
    Candidate,
    CandidateOrigin,
    ConfirmedAnswer,
    DirectTypedInteraction,
    DirectVoiceInteraction,
    ExportRecord,
    ExportStatus,
    GuidedFinalInteraction,
    ObjectReference,
    Placement,
    PlacementCapability,
    QuestionDefinition,
    QuestionSetupProvenance,
    QuestionState,
    RephraseRecord,
    SelectedRephraseInteraction,
    StudentAttribution,
    StudentEditInteraction,
)

_WORKFLOW_EXPORTS = frozenset(
    {
        "ConfirmationResult",
        "ConfirmedAnswerForExport",
        "ExportStartResult",
        "ReviewIssueResult",
        "begin_revision",
        "accept_question_setup",
        "complete_export",
        "confirm_candidate",
        "confirmed_answers_for_export",
        "fail_export",
        "issue_review",
        "record_rephrase",
        "replace_candidate",
        "replace_question_setup",
        "reset_question_setup",
        "require_active",
        "require_current_version",
        "require_question_setup_verified",
        "start_export",
    }
)


def __getattr__(name: str) -> object:
    """Load workflow operations lazily so security primitives can import models safely."""

    if name in _WORKFLOW_EXPORTS:
        from backend.domain import workflow

        return getattr(workflow, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "AssignmentExpired",
    "AssignmentManifest",
    "AssignmentStatus",
    "AssignmentVersionConflict",
    "Candidate",
    "CandidateNotFound",
    "CandidateOrigin",
    "ConfirmationResult",
    "ConfirmedAnswer",
    "ConfirmedAnswerForExport",
    "DirectTypedInteraction",
    "DirectVoiceInteraction",
    "DomainError",
    "ExportRecord",
    "ExportStartResult",
    "ExportStatus",
    "GuidedFinalInteraction",
    "InvalidCandidate",
    "InvalidCandidateOrigin",
    "InvalidQuestionSetup",
    "NoConfirmedAnswers",
    "ObjectReference",
    "Placement",
    "PlacementCapability",
    "QuestionDefinition",
    "QuestionNotFound",
    "QuestionSetupLocked",
    "QuestionSetupProvenance",
    "QuestionSetupUnverified",
    "QuestionState",
    "RephraseRecord",
    "ReviewIssueResult",
    "ReviewTokenExpired",
    "ReviewTokenInvalid",
    "ReviewTokenStale",
    "SelectedRephraseInteraction",
    "StudentAttribution",
    "StudentEditInteraction",
    "accept_question_setup",
    "begin_revision",
    "complete_export",
    "confirm_candidate",
    "confirmed_answers_for_export",
    "fail_export",
    "issue_review",
    "record_rephrase",
    "replace_candidate",
    "replace_question_setup",
    "require_active",
    "require_current_version",
    "require_question_setup_verified",
    "reset_question_setup",
    "start_export",
]
