"""Small service protocol consumed by the HTTP transport."""

from __future__ import annotations

from typing import Any, Protocol


class AssignmentService(Protocol):
    async def create_assignment(self, **kwargs: Any) -> Any: ...

    async def get_assignment(self, **kwargs: Any) -> Any: ...

    async def read_source(self, **kwargs: Any) -> Any: ...

    async def get_page_context(self, **kwargs: Any) -> Any: ...

    async def create_candidate(self, **kwargs: Any) -> Any: ...

    async def request_rephrase(self, **kwargs: Any) -> Any: ...

    async def create_review(self, **kwargs: Any) -> Any: ...

    async def confirm_answer(self, **kwargs: Any) -> Any: ...

    async def begin_revision(self, **kwargs: Any) -> Any: ...

    async def create_export(self, **kwargs: Any) -> Any: ...

    async def get_export(self, **kwargs: Any) -> Any: ...

    async def read_export(self, **kwargs: Any) -> Any: ...

    async def issue_realtime_credential(self, **kwargs: Any) -> Any: ...
